-- Create a store products table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  stock INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert dummy inventory items
INSERT INTO public.products (title, price, stock)
VALUES 
  ('Wireless Mechanical Keyboard', 89.99, 15),
  ('Ergonomic Gaming Mouse', 49.50, 30),
  ('UltraWide 4K Monitor', 349.99, 8)
ON CONFLICT DO NOTHING;

-- jika ingin di push ulang, tidak bisa dikarenakan riwayat 
-- schema migrasinya tidak ikut kehapus jadi gunakan command ini di supabase cli 

-- DELETE FROM supabase_migrations.schema_migrations;
